'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Elementos
    Public Property ElementoId As Integer
    Public Property Nombre As String
    Public Property ModuloFk As Integer
    Public Property TipoElementoFk As Integer
    Public Property Describe As String
    Public Property Ruta As String
    Public Property ElementoPadreFk As Nullable(Of Integer)

    Public Overridable Property Modulos As Modulos
    Public Overridable Property TiposElementos As TiposElementos
    Public Overridable Property Menus As ICollection(Of Menus) = New HashSet(Of Menus)
    Public Overridable Property Opciones As ICollection(Of Opciones) = New HashSet(Of Opciones)

End Class
