'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Estados
    Public Property EstadoId As Integer
    Public Property Nombre As String
    Public Property ModuloFk As Integer
    Public Property Describe As String

    Public Overridable Property Empleados As ICollection(Of Empleados) = New HashSet(Of Empleados)
    Public Overridable Property Modulos As Modulos

End Class
