'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class AndiTecnicaEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=AndiTecnicaEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property Autorizaciones() As DbSet(Of Autorizaciones)
    Public Property Botones() As DbSet(Of Botones)
    Public Property Elementos() As DbSet(Of Elementos)
    Public Property Empleados() As DbSet(Of Empleados)
    Public Property Estados() As DbSet(Of Estados)
    Public Property Menus() As DbSet(Of Menus)
    Public Property Modulos() As DbSet(Of Modulos)
    Public Property Opciones() As DbSet(Of Opciones)
    Public Property Perfiles() As DbSet(Of Perfiles)
    Public Property Permisos() As DbSet(Of Permisos)
    Public Property TiposElementos() As DbSet(Of TiposElementos)
    Public Property Usuarios() As DbSet(Of Usuarios)

End Class
