'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Modulos
    Public Property ModuloId As Integer
    Public Property Nombre As String
    Public Property Prefijo As String
    Public Property Describe As String

    Public Overridable Property Estados As ICollection(Of Estados) = New HashSet(Of Estados)
    Public Overridable Property Menus As ICollection(Of Menus) = New HashSet(Of Menus)

End Class
