'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Permisos
    Public Property PermisoId As Integer
    Public Property PerfilFk As Integer
    Public Property OpcionFk As Integer
    Public Property Valor As Boolean

    Public Overridable Property Opciones As Opciones
    Public Overridable Property Perfiles As Perfiles

End Class
