'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Proveedores
    Public Property ProveedorId As Integer
    Public Property Nombre As String
    Public Property Identificacion As String
    Public Property Direccion As String
    Public Property PaisFk As Integer
    Public Property Correo As String
    Public Property Telefono As String
    Public Property PlazoFk As Integer
    Public Property Notas As String
    Public Property Creado As Date
    Public Property Modificado As Date
    Public Property EstadoFk As Integer

    Public Overridable Property Estados As Estados

End Class
