'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Usuarios
    Public Property UsuarioId As Integer
    Public Property Usuario As String
    Public Property Clave As String
    Public Property PerfilFk As Integer
    Public Property EmpleadoFk As Integer
    Public Property Creado As Date
    Public Property Modificado As Date
    Public Property Estado As Nullable(Of Integer)

    Public Overridable Property Empleados As Empleados
    Public Overridable Property Perfiles As Perfiles
    Public Overridable Property Estados As Estados

End Class
