'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Usuario
    
    '''<summary>
    '''lkb_buscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lkb_buscar As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lkb_agregar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lkb_agregar As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lkb_editar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lkb_editar As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lkb_guardar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lkb_guardar As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lkb_eliminar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lkb_eliminar As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lkb_salir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lkb_salir As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''pnl_form control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_form As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''Lbl_Estado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Lbl_Estado As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_Estado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Estado As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbl_usuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_usuario As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_usuario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_usuario As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbl_perfil control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_perfil As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbx_Perfiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbx_Perfiles As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lbl_Empleado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Empleado As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbx_Empleados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbx_Empleados As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lbl_clave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_clave As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_clave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_clave As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbl_confirmaclave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_confirmaclave As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_confirmaclave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_confirmaclave As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''pnl_list control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_list As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''pnl_buscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnl_buscar As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lbl_buscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_buscar As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_bucar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_bucar As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btn_filtrar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_filtrar As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''grd_Perfiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grd_Perfiles As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''hdf_id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdf_id As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''ods_Perfiles control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ods_Perfiles As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''ods_Empleados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ods_Empleados As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As AndiTecnica.Web.Principal
        Get
            Return CType(MyBase.Master,AndiTecnica.Web.Principal)
        End Get
    End Property
End Class
